Developer-DAO/academy-turbo

apps/academy/src/components/Header.tsx
apps/academy/src/components/Layout.tsx
apps/academy/src/pages/_app.tsx
packages/ui/package.json

- sharing styles from ui package to academy app
- work on header component considering our future layout (needs more work)

feat: sharing styles and header layout attempt

---

packages/ui/src/components/Banners/LearnWeb3Banner.tsx
packages/ui/src/components/Banners/PartnerBanner.stories.ts
packages/ui/src/components/Banners/PartnerBanner.tsx
packages/ui/src/styles.css

updated the home page banners as per the new designs so far available on figma.
fixes #22 
fixes #23

feat: home page banner updates

---

apps/academy/src/content/intro-to-ethereum/1.mdx
apps/academy/src/content/intro-to-ethereum/2.mdx
apps/academy/src/content/intro-to-ethereum/3.mdx
apps/academy/src/quizzes/intro-to-ethereum/quiz-eth-intro-1.json
apps/academy/src/quizzes/intro-to-ethereum/quiz-eth-intro-2.json
apps/academy/src/quizzes/intro-to-ethereum/quiz-eth-intro-3.json

- ports over Intro to Ethereum track (3 lessons)
- new `src/content/track-name/` directory pattern introduced
- new `src/quizzes/track-name/` directory pattern introduced
- note: feel free to change directory and file naming conventions as needed
- note: the first lesson has two check-in quizzes that i chose to exclude for this first pass. will introduce in another PR once we're ready for them.

feat: port intro to eth track

---

apps/academy/src/components/AboutCourse.tsx
apps/academy/src/components/Header.tsx
apps/academy/src/components/LessonLayout.tsx
apps/academy/src/components/mdx/Components.tsx
apps/academy/src/components/mdx/Quiz.tsx
apps/academy/src/components/mdx/QuizStatusChecker.tsx
apps/academy/src/components/mdx/SideDrawer.tsx
apps/academy/src/contexts/AppContextProvider.tsx
apps/academy/src/pages/_app.tsx
apps/academy/src/pages/intro-to-ethereum/1.mdx
apps/academy/src/pages/intro-to-ethereum/2.mdx
apps/academy/src/pages/intro-to-ethereum/3.mdx
apps/academy/src/pages/track/[trackID].tsx
apps/academy/src/server/api/root.ts
packages/database/index.ts
packages/database/prisma/schema.prisma
packages/database/prisma/seed.ts
packages/ui/package.json
packages/ui/src/components/Button/Button.tsx
packages/ui/src/components/index.ts
packages/ui/src/components/ui/badge.tsx
packages/ui/src/components/ui/dialog.tsx
packages/ui/src/components/ui/drawer.tsx
packages/ui/src/components/ui/toast.tsx
packages/ui/src/components/ui/toaster.tsx
packages/ui/src/components/ui/use-toast.tsx
pnpm-lock.yaml

- updated quiz component to use shadcn and tailwind styles
- installed new shadcn components
- this closes #46

feat: migrated quiz component and related dependencies

---

apps/academy/src/components/LessonLayout.tsx
apps/academy/src/components/mdx/Quiz.tsx

feat: some small css fixes and enhancements

---

apps/academy/src/components/Header.tsx
packages/ui/package.json
packages/ui/src/components/Footer/Footer.tsx
packages/ui/src/components/Topbar/TopBar.tsx
packages/ui/src/components/index.ts
packages/ui/src/components/ui/tooltip.tsx
pnpm-lock.yaml

- added social url  and links on Footer component
- created a small Tooltip with detail text for the link logos and text
- added D_D handbook to community button for the moment

feat: fixed footer links among other small stuff

---

apps/academy/src/components/Header.tsx
apps/academy/src/components/Layout.tsx
apps/academy/src/components/TrackAuthor.tsx
apps/academy/src/components/TracksLayout.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx

- enhanced tracks layout mobile styles
- track page mobile styles
- layout header mobile styles
- layout footer mobile styles

feat: enhanced tracks layout and layout header and footer mobile styles

---

apps/academy/src/components/AboutCourse.tsx
apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/index.tsx

- imported new erc-20 track which now includes:
Introduction to Smart Contract Development with Solidity;
Your own ERC-20 Token: A Step-by-Step Guide using Foundry
- fixed and updated tags on tracks page and lesson pages 
Need to add descriptions to front matter to capture lesson descriptions (we can prioritise implementing them at a later stage)
Contributors and reviewers need to be added later. We needed to temporarily remove them to be able to build the project.

feat: add erc-20 track, fixed tags styling

---

apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/fundamentals/index.tsx
apps/academy/src/pages/tracks/index.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx

- update all `description`s in `tracksArray` in `/src/tracks/index.tsx` file
- update `trackDescription`  in all   `/src/tracks/<track-name>/index.tsx` files
- I gave the `erc-20 track` an ambitious description
p.s. Marc - I don't know what your bandwidth is in the coming week, but I made the assumption that it is stretched, so I took the liberty of giving all your tutorials descriptions, so that at least we have something relatively meaningful there. I changed the titles to the originals. I think they got simplified in the content migration with some copy and pasting. I incorporated the original descriptions as best I could, as they were a bit short on detail on their own for the purposes of this whole exercise, i.e using tabs/cards. 
p.s. I will **not** be offended if you update it with …

feat: update/create remaining titles/descriptions for tracks/lessons

---

TODO.md
apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
apps/academy/src/pages/tracks/intro-to-ethereum/1.mdx
apps/academy/src/pages/tracks/intro-to-ethereum/2.mdx
apps/academy/src/pages/tracks/intro-to-ethereum/3.mdx
apps/academy/src/pages/tracks/nft-solidity/1.mdx
apps/academy/src/pages/tracks/nft-solidity/2.mdx
apps/academy/src/pages/tracks/nft-solidity/3.mdx
apps/academy/src/pages/tracks/nft-solidity/4.mdx

- fixed bad quizzes paths on all tracks folder lessons
- updated TODOs list file

feat: fixed bad quizzes paths on all tracks folder lessons

---

apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/fundamentals/index.tsx
apps/academy/src/pages/tracks/index.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
apps/academy/src/pages/tracks/nft-solidity/index.tsx

feat: update description tags on lessons and tracks

---

apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
apps/academy/src/pages/tracks/intro-to-ethereum/1.mdx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
apps/academy/src/pages/tracks/nft-solidity/1.mdx
apps/academy/src/pages/tracks/nft-solidity/2.mdx
apps/academy/src/pages/tracks/nft-solidity/3.mdx
apps/academy/src/pages/tracks/nft-solidity/4.mdx

- smol fix - path to Dev's Guide to Eth parts 2 and 3 needed re-configured properly in `/tracks/into-to-ethereum/index.ts` in `lessonsArray`
- commented out prompts to learner in lesson body to set pomodoro timer. 
- where it seemed appropriate, I replaced that with a prompt "Go touch grass 😊 🌱"  - I didn't overdo it, e.g. I added one in Dev's Guide to Eth part 1, but didn't add any in parts 2 and 3, since there were no quizzes

chore: Fix paths to some lessons. Prompt learner to take breaks

---

apps/academy/src/pages/tracks/nft-solidity/5.mdx

Ran through Lesson 5 and made some initial fixes.

Lesson5: Grammar and text tweaks

---

pnpm-lock.yaml

- restored `pnpm-lock.yml` after running `pnpm install`

feat: fixed branch afte running pnpm install

---

apps/academy/src/pages/tracks/fundamentals/code-editors.mdx
apps/academy/src/pages/tracks/fundamentals/decentralized-storage.mdx
apps/academy/src/pages/tracks/fundamentals/install-npm.mdx
apps/academy/src/pages/tracks/fundamentals/nft-hosting.mdx

- updated John-mac.eth's name fields as best as possible
- moved a paragraph in the Decentralised Storage lesson: apps/academy/src/pages/tracks/fundamentals/decentralized-storage.mdx

chore: minor nitpicks: fundamentals lessons and authors

---

apps/academy/src/components/ConnectButton.tsx
apps/academy/src/components/mdx/LessonQuestionsModal.tsx
packages/ui/src/components/Footer/Footer.tsx

- fixed connected avatar status styling (the border was offset)
- changed lessonQuestionModal width to a bigger size
- added Developer DAO website URL on the D_D footer logo using <a> and about _blank prop
some screenshots for reference:
wallet avatar before:
wallet avatar updated:
LessonQuestionModal component's width before:
LessonQuestionModal component's width updated:
and the Developer DAO website new URL in the footer's logo with a hover tooltip:
_Note: Open to suggestions or comments. I just changed/updated this small details because they were too obvious to me and wanted to keep adding things to the mvp version._

feat: fixed avatar, fixed question modal and added footer D_D url

---

apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
apps/academy/src/pages/tracks/nft-solidity/1.mdx
apps/academy/src/pages/tracks/nft-solidity/2.mdx
apps/academy/src/pages/tracks/nft-solidity/3.mdx

- fix a couple occasions where bullet points were broken, pointed out in this comment https://github.com/Developer-DAO/academy-turbo/pull/107#pullrequestreview-1847789241
(screenshots from prior to font changes)
before:
after:

fix: content broken bullet points

---

apps/academy/src/pages/_app.tsx

fix: rainbowkit wallet list order

---

apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
apps/academy/src/pages/tracks/nft-solidity/index.tsx
packages/database/prisma/seed.ts

- submitting minor changes update on page components name
- sharing seed.ts db code example used for updates

feat: commiting minor changes and seeder code example update

---

apps/academy/src/components/Spinner.tsx
apps/academy/src/components/mdx/Quiz.tsx
apps/academy/src/components/mdx/QuizStatusChecker.tsx
apps/academy/src/contexts/AppContext.tsx
apps/academy/src/contexts/AppContextProvider.tsx
apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/fundamentals/index.tsx
apps/academy/src/pages/tracks/index.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
apps/academy/src/pages/tracks/nft-solidity/index.tsx
apps/academy/src/server/api/root.ts
apps/academy/src/server/api/routers/lessons.ts
apps/academy/src/server/api/routers/tracks.ts
packages/database/prisma/schema.prisma
packages/database/prisma/seed.ts
packages/ui/src/components/Cards/TrackCard.tsx

- finished backend fetch calls integration
- created tracksRouter for trcp
- created small spinner component TBR
Note:
fetched tracks but tags are having some typescript typing issue with prisma type and this appeared after starting use the `include: true` flag on the fetch call_
Next: order the lessons on each track page

feat: backend integration and created a small spinner component

---

apps/academy/src/contexts/AppContext.tsx
apps/academy/src/contexts/AppContextProvider.tsx

- commenting code to avoid console errors

feat: commented code to avoid errors

---

apps/academy/src/pages/tracks/index.tsx
apps/academy/src/server/api/routers/tracks.ts

- including tags tracks on tracks list page
-

feat: including tags tracks on tracks list page

---

apps/academy/src/components/Header.tsx
apps/academy/src/components/ThemeToggleButton.tsx

- theme toggle button hided 
- abstracted in a new component
this closes #135

feat: theme toggle button hided and abstracted in a new component

---

apps/academy/src/components/Header.tsx
packages/ui/src/components/Topbar/TopBar.tsx

- updated code to trigger deploy

feat: updated code to run deploy

---

apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
apps/academy/src/pages/tracks/nft-solidity/1.mdx
apps/academy/src/pages/tracks/nft-solidity/2.mdx
apps/academy/src/pages/tracks/nft-solidity/4.mdx
apps/academy/src/pages/tracks/nft-solidity/5.mdx

- remove (hopefully) all references to pomodoro
- revise text a little bit to still encourage learner to take breaks

chore: remove pomodoro references. 

---

apps/academy/src/components/mdx/LessonInformationalModal.tsx
apps/academy/src/components/mdx/Question.tsx
apps/academy/src/components/mdx/Quiz.tsx
apps/academy/src/components/mdx/QuizCompletedModals.tsx
apps/academy/src/components/mdx/QuizStatusChecker.tsx
apps/academy/src/pages/index.tsx
packages/ui/src/components/Banners/LearnWeb3Banner.tsx
packages/ui/src/components/Banners/PartnerBanner.tsx
packages/ui/src/components/Footer/Footer.tsx

- changed open status for completed quizes
- deleted the method to show the Letter option on quiz options
this closes #163 and #164
Buttons
Modals

feat: mvp fixes

---

apps/academy/src/server/api/routers/lessons.ts

- created new api request method

feat: created new api request method

---

apps/academy/src/components/mdx/Quiz.tsx

- quick & dirty attempt to fix unusable mobile quiz modals

fix: unreachable btns quiz modal

---

apps/academy/src/pages/404.tsx
apps/academy/src/pages/fundamentals/index.tsx
apps/academy/src/pages/index.tsx
apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
apps/academy/src/pages/tracks/index.tsx
apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
apps/academy/src/pages/tracks/nft-solidity/index.tsx
apps/academy/src/pages/tracks/oracles-api3/index.tsx
apps/academy/src/pages/tracks/web3-python/index.tsx

- added PageSEOLayout for all pages (homepage, trackspage, fundamentalspage, each track page)
- cleaned old commented code
- lessons pages remaining

feat: added PageSEOLayout for all pages, lessons pages remaining

---

apps/academy/src/components/mdx/Quiz.tsx

- staging -> main
- deploy quiz modal bug fix

Staging to Main: quiz modal bug fix

---

apps/academy/package.json
apps/academy/src/pages/_app.tsx
pnpm-lock.yaml

feat: adding vercel analytics

---

apps/academy/package.json
apps/academy/src/components/mdx/Quiz.tsx
apps/academy/src/pages/_app.tsx
pnpm-lock.yaml

- adding vercel analytics (for the moment until better solution)
- I will regulary check Analytics expenses on Vercel dashboard
this closes #193

Staging to Main: adding vercel analytics

---

apps/academy/src/components/LessonLayout.tsx
apps/academy/src/pages/fundamentals/index.tsx
apps/academy/src/server/api/routers/lessons.ts

- starting academy fetching implementation

chore: starting academy fetching implementation

---

apps/academy/src/pages/tracks/arweave-101/1.mdx
apps/academy/src/pages/tracks/arweave-101/2.mdx
apps/academy/src/pages/tracks/arweave-101/3.mdx
apps/academy/src/pages/tracks/arweave-101/index.tsx

- fixed author avatar file name reference to be loaded properly
- added db entries on staging only, still need description and Lesson's tags

feat: fixed author avatar file name reference

---

apps/academy/src/components/Layout.tsx
package.json

This PR comments out the code relevant to email capture and verification.

chore: commenting out email features

---

apps/academy/src/components/mdx/Question.tsx

-  fixed checkpoint questions submit for multiple answers

feat: fixed checkpoint questions submit for multiple answers

---

apps/academy/src/pages/tracks/arweave-101/1.mdx
apps/academy/src/pages/tracks/arweave-101/2.mdx
apps/academy/src/pages/tracks/arweave-101/3.mdx

- typo and clarity fixes for claim modal

fix: claim modal typos

---

apps/academy/src/pages/tracks/arweave-101/4.mdx

fix: center and italicize figure titles in arweave 101: L4

fix: style on figure labels

---

apps/academy/src/pages/tracks/arweave-101/1.mdx
apps/academy/src/pages/tracks/arweave-101/2.mdx
apps/academy/src/pages/tracks/arweave-101/3.mdx
apps/academy/src/pages/tracks/arweave-101/4.mdx
apps/academy/src/pages/tracks/arweave-101/5.mdx
apps/academy/src/pages/tracks/arweave-201/1.mdx

quick update to quest text data for all AR.IO courses as agreed with their team

Chore: update ar quest text to remove screenshot ask
